---
title: "optimize denovo Dicaeum assembly"
author: "Devon DeRaad"
date: '2022-11-18'
output: html_document
---

### Install and load packages
```{r}
library(RADstackshelpR)
```

### Optimize 'm'
```{r}
#optimize_m function will generate summary stats on your 5 iterative runs
#input can be full path to each file, or just the file name if the vcf files are in your working directory
m.out<-optimize_m(m3="/Users/devder/Desktop/phil.dicaeum/m3.vcf",
           m4="/Users/devder/Desktop/phil.dicaeum/m4.vcf",
           m5="/Users/devder/Desktop/phil.dicaeum/m5.vcf",
           m6="/Users/devder/Desktop/phil.dicaeum/m6.vcf",
           m7="/Users/devder/Desktop/phil.dicaeum/m7.vcf")
           
#visualize depth of coverage
vis_depth(output = m.out)

#visualize the effect of varying m on the number of SNPs retained
vis_snps(output = m.out, stacks_param = "m")

#visualize the effect of varying m on the number of loci retained
vis_loci(output = m.out, stacks_param = "m")
```


### Optimize 'M'
```{r}
#optimize_bigM function will generate summary stats on your 5 iterative runs
#input can be full path to each file, or just the file name if the vcf files are in your working directory
bigM.out<-optimize_bigM(M1="/Users/devder/Desktop/phil.dicaeum/bigM1.vcf",
           M2="/Users/devder/Desktop/phil.dicaeum/bigM2.vcf",
           M3="/Users/devder/Desktop/phil.dicaeum/bigM3.vcf",
           M4="/Users/devder/Desktop/phil.dicaeum/bigM4.vcf",
           M5="/Users/devder/Desktop/phil.dicaeum/bigM5.vcf",
           M6="/Users/devder/Desktop/phil.dicaeum/bigM6.vcf",
           M7="/Users/devder/Desktop/phil.dicaeum/bigM7.vcf",
           M8="/Users/devder/Desktop/phil.dicaeum/bigM8.vcf")
           
#use this function to visualize the effect of varying 'M' on the number of SNPs retained
vis_snps(output = bigM.out, stacks_param = "M")

#visualize the effect of varying 'M' on the number of polymorphic loci retained
vis_loci(output = bigM.out, stacks_param = "M")
```

### Optimize 'n'
```{r}
#optimize_bigM function will generate summary stats on your 5 iterative runs
#input can be full path to each file, or just the file name if the vcf files are in your working directory
n.out<-optimize_n(nequalsMminus1="/Users/devder/Desktop/phil.dicaeum/n7.vcf",
           nequalsM="/Users/devder/Desktop/phil.dicaeum/n8.vcf",
           nequalsMplus1="/Users/devder/Desktop/phil.dicaeum/n9.vcf")
           
#use this function to visualize the effect of varying 'n' on the number of SNPs retained
vis_snps(output = n.out, stacks_param = "n")

#visualize the effect of varying 'n' on the number of polymorphic loci retained
vis_loci(output = n.out, stacks_param = "n")
```

### make summary figure
```{r}
#load gridExtra package to combine ggplot visualizations
library(gridExtra)

#combine all of these prior visulizations in a single list
gl<-list()
gl[[1]]<-vis_depth(output = m.out)
gl[[2]]<-vis_snps(output = m.out, stacks_param = "m")
gl[[3]]<-vis_loci(output = m.out, stacks_param = "m")
gl[[4]]<-vis_snps(output = bigM.out, stacks_param = "M")
gl[[5]]<-vis_loci(output = bigM.out, stacks_param = "M")
gl[[6]]<-vis_snps(output = n.out, stacks_param = "n")
gl[[7]]<-vis_loci(output = n.out, stacks_param = "n")

#visualize each item of the list as part of a single grid
grid.arrange(grobs = gl, widths = c(1,1,1,1,1,1),
  layout_matrix = rbind(c(1,1,2,2,3,3),
                        c(4,4,4,5,5,5),
                        c(6,6,6,7,7,7))
)

#remotes::install_github("idmn/ggview")
#library(ggview)
#ggview(units="in", width=4, height=4)
#save
g<-arrangeGrob(grobs = gl, widths = c(1,1,1,1,1,1),
  layout_matrix = rbind(c(1,1,2,2,3,3),
                        c(4,4,4,5,5,5),
                        c(6,6,6,7,7,7))
)

#library(ggplot2)
#ggsave(file="~/Desktop/phil.dicaeum/denovo.optimize.pdf", g, units="in",width=8,height=8) #saves g
```

